from enum import StrEnum


class CompanyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    NON_ACTIVE = "NON_ACTIVE"
    BLACKLISTED = "BLACKLISTED"
    ARCHIVED = "ARCHIVED"


class OrgType(StrEnum):
    PRIVE = "PRIVE"
    ETATIQUE = "ETATIQUE"
    MULTINATIONAL = "MULTINATIONAL"


class ActivitySector(StrEnum):
    PHARMACEUTIQUE = "PHARMACEUTIQUE"
    AUTOMOBILE = "AUTOMOBILE"
    AGROALIMENTAIRE = "AGRO_ALIMENTAIRE"
    CONSTRUCTION = "CONSTRUCTION"
    IMMOBILIER = "IMMOBILIER"
    ENERGIE = "ENERGIE"
    TRANSPORT = "TRANSPORT"
    TELECOMMUNICATION = "TELECOMMUNICATION"
    TECHNOLOGIE = "TECHNOLOGIE"
    BANQUE = "BANQUE"
    ASSURANCE = "ASSURANCE"
    SERIVCES = "SERVICES"
    CONSEILS = "CONSEILS"
    AUTRES = "AUTRES"
