"""add_formateur_formation

Revision ID: 05d9d977c558
Revises: a3ffcae59fd7
Create Date: 2026-04-14 23:54:31.633112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d9d977c558'
down_revision: Union[str, Sequence[str], None] = 'a3ffcae59fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formateurs',
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('specialite', sa.Enum('rh', 'developpement_personnel', 'management', 'team_building', 'coaching', 'sst', 'juridique', 'informatique', 'autre', name='domainformation'), nullable=True),
    sa.Column('niveau_expertise', sa.Enum('junior', 'confirme', 'senior', 'expert', name='niveauexpertise'), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'NON_ACTIVE', name='formateurstatus'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formations',
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domaine', sa.Enum('rh', 'developpement_personnel', 'management', 'team_building', 'coaching', 'sst', 'juridique', 'informatique', 'autre', name='domainformation'), nullable=False),
    sa.Column('type', sa.Enum('POUR_ENTREPRISE', 'PARTICULIER', name='typeformation'), nullable=False),
    sa.Column('niveau', sa.Enum('debutant', 'intermediaire', 'avance', 'tous_niveaux', name='niveauformation'), nullable=False),
    sa.Column('duree_jours', sa.Integer(), nullable=False),
    sa.Column('heures_par_jour', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('certifiante', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIBLE', 'NON_DISPONIBLE', name='statusformation'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('formateur_formations',
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('formation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('principal', 'co_formateur', 'remplacant', 'superviseur', name='roleformateur'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formateur_id', 'formation_id', name='uq_formateur_formation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formateur_formations')
    op.drop_table('formations')
    op.drop_table('formateurs')
    # ### end Alembic commands ###
