"""add_salle_model

Revision ID: 2fdbb16e28e0
Revises: c88ae8d77128
Create Date: 2026-05-11 08:58:03.719349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdbb16e28e0'
down_revision: Union[str, Sequence[str], None] = 'c88ae8d77128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIBLE', 'MAINTENANCE', name='sallestate'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salles')
    # ### end Alembic commands ###
