"""fix_model_session

Revision ID: 3231c9e0ed7b
Revises: 2e3fc24e73a8
Create Date: 2026-05-13 23:16:31.851514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3231c9e0ed7b'
down_revision: Union[str, Sequence[str], None] = '2e3fc24e73a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
