"""add_formateur_rate

Revision ID: 32be2f6c8fe8
Revises: 4a60a056c0ec
Create Date: 2026-05-05 01:19:11.183261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be2f6c8fe8'
down_revision: Union[str, Sequence[str], None] = '4a60a056c0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formateurs', sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('formateurs', sa.Column('ville', sa.String(), nullable=True))
    op.add_column('formateurs', sa.Column('year_of_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formateurs', 'year_of_experience')
    op.drop_column('formateurs', 'ville')
    op.drop_column('formateurs', 'daily_rate')
    # ### end Alembic commands ###
