"""added_session_plan

Revision ID: 4a60a056c0ec
Revises: c852c6d12d38
Create Date: 2026-04-29 19:54:17.511983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a60a056c0ec'
down_revision: Union[str, Sequence[str], None] = 'c852c6d12d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionplans',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'LOCKED', name='sessionplanstatus'), nullable=False),
    sa.Column('expected_students', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.Enum('IN_HOUSE', 'HOTEL', name='locationtype'), nullable=False),
    sa.Column('venue_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_student', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionplans')
    # ### end Alembic commands ###
