"""add_session_model

Revision ID: 8c8c96d9b9f1
Revises: 2fdbb16e28e0
Create Date: 2026-05-11 15:21:48.202374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8c96d9b9f1'
down_revision: Union[str, Sequence[str], None] = '2fdbb16e28e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('formation_id', sa.UUID(), nullable=False),
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('salle_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'EN_COURS', 'VALIDATION', 'VALIDE', 'TERMINEE', 'CANCELLED', 'POSTPONED', name='sessionstate'), nullable=False),
    sa.Column('planning_type', sa.Enum('BLOC', 'RECURRENT', name='planningtype'), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
