"""add_opportunity_model

Revision ID: 91de483b1ac2
Revises: 05d9d977c558
Create Date: 2026-04-28 00:46:08.587127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91de483b1ac2'
down_revision: Union[str, Sequence[str], None] = '05d9d977c558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'NEED_ANALYSIS', 'PROPOSAL', 'NEGOTITATION', 'WON', 'LOST', 'CANCELLED', name='opportunity_states'), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
