"""recreate clean enum

Revision ID: c852c6d12d38
Revises: 91de483b1ac2
Create Date: 2026-04-28 14:47:54.296223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c852c6d12d38'
down_revision: Union[str, Sequence[str], None] = '91de483b1ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'NEED_ANALYSIS', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', 'CANCELLED', name='opportunity_states'), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
