"""crm_company_model

Revision ID: d3e97250acbe
Revises: 
Create Date: 2026-03-25 15:04:36.410083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e97250acbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('raison_sociale', sa.String(length=150), nullable=False),
    sa.Column('nom_commercial', sa.String(length=150), nullable=True),
    sa.Column('organization_type', sa.Enum('PRIVE', 'ETATIQUE', 'MULTINATIONAL', name='org_type_enum'), nullable=False),
    sa.Column('activity_sector', sa.Enum('PHARMACEUTIQUE', 'AUTOMOBILE', 'AGROALIMENTAIRE', 'CONSTRUCTION', 'IMMOBILIER', 'ENERGIE', 'TRANSPORT', 'TELECOMMUNICATION', 'TECHNOLOGIE', 'BANQUE', 'ASSURANCE', 'SERIVCES', 'CONSEILS', 'AUTRES', name='activity_sector_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NON_ACTIVE', 'BLACKLISTED', 'ARCHIVED', name='company_status_enum'), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('rc_number', sa.String(length=20), nullable=False),
    sa.Column('nif_number', sa.String(length=20), nullable=False),
    sa.Column('ai_number', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_number'),
    sa.UniqueConstraint('nif_number'),
    sa.UniqueConstraint('rc_number')
    )
    op.create_index('ix_companies_legal_name', 'companies', ['raison_sociale'], unique=False)
    op.create_index(op.f('ix_companies_nom_commercial'), 'companies', ['nom_commercial'], unique=False)
    op.create_index(op.f('ix_companies_organization_type'), 'companies', ['organization_type'], unique=False)
    op.create_index(op.f('ix_companies_raison_sociale'), 'companies', ['raison_sociale'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_index('ix_companies_trade_name', 'companies', ['nom_commercial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_trade_name', table_name='companies')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_raison_sociale'), table_name='companies')
    op.drop_index(op.f('ix_companies_organization_type'), table_name='companies')
    op.drop_index(op.f('ix_companies_nom_commercial'), table_name='companies')
    op.drop_index('ix_companies_legal_name', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
