"""update_session_seq_number

Revision ID: f39de01c6ba2
Revises: 3231c9e0ed7b
Create Date: 2026-05-18 11:22:58.995458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39de01c6ba2'
down_revision: Union[str, Sequence[str], None] = '3231c9e0ed7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_number', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'sessions', ['session_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'session_number')
    # ### end Alembic commands ###
